app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'userController@index')->name('index');
Route::get('/admin/current_status', 'userController@currentStatus')->name('currentStatus');

Route::group(['middleware' => ['auth'], 'prefix' => "admin/quizzes", 'as' => "admin.quizzes."], function () {
    Route::get('/', function () {
        return redirect('/admin/quizzes/1/edit');
    });
    Route::get('{id}/edit', 'quizController@edit')->name('edit');
    Route::post('question_add/{quiz_id}', 'quizController@addQuestion')->name('question_add');
    Route::post('answer_add/{quiz_id}', 'quizController@addAnswer')->name('answer_add');
    Route::get('answers/{question_id}', 'quizController@answers')->name('answers');
    Route::delete('{id}/delete', 'quizController@delete')->name('delete');
    Route::post('quizzes/{id}/init_question', 'quizController@initQuestion')->name('init_question');
    Route::post('{id}/upload_question_file', 'quizController@uploadQuestionFile')->name('upload_question_file');
    Route::post('{id}/upload_answer_file', 'quizController@uploadAnswerFile')->name('upload_answer_file');
    Route::get('{id}/question_file', 'quizController@questionFile')->name('question_file');
    Route::get('{id}/answer_file', 'quizController@answerFile')->name('answer_file');
    Route::delete('{id}/delete_question_file', 'quizController@deleteQuestionFile')->name('delete_question_file');
    Route::delete('{id}/delete_answer_file', 'quizController@deleteAnswerFile')->name('delete_answer_file');
    Route::delete('{id}/delete_course_image', 'quizController@deleteCourseImage')->name('delete_course_image');
    Route::delete('{id}/delete_promo', 'quizController@deletePromo')->name('delete_promo');
    Route::patch('{id}/update', 'quizController@update')->name('update');
    Route::patch('{id}/update_answers', 'quizController@updateAnswers')->name('update_answers');
});


Route::group(['middleware' => ['auth'], 'prefix' => 'admin/users', 'as' => 'admin.users.'], function () {
    Route::get('/{status}', 'UserController@index')->name('index');

    Route::post('init', 'UserController@init')->name('init');
    Route::get('{id}/edit', 'UserController@edit')->name('edit');
    Route::delete('{id}/delete', 'UserController@delete')->name('delete');
    Route::post('{id}/recommission', 'UserController@recommission')->name('recommission');
    Route::get('create', 'UserController@create')->name('create');
    Route::delete('delete_multiple', 'UserController@deleteMultiple')->name('delete_multiple');
    Route::post('store', 'UserController@store')->name('store');
    Route::patch('{id}/update', 'UserController@update')->name('update');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'admin/user_test', 'as' => 'admin.user_test.'], function () {
    Route::get('/', 'volunteersTestController@index')->name('index');

    Route::get('startTest/{user_id}', 'volunteersTestController@startTest')->name('start_test');
    Route::post('answerQuestion', 'volunteersTestController@answerQuestion')->name('answer_question');
    Route::get('endTest', 'volunteersTestController@endTest')->name('end_test');
    
});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/material", 'as' => "admin.material."], function () {
    Route::get('/', 'materialController@index')->name('index');
    Route::post('init', 'materialController@init')->name('init');
    Route::get('{id}/edit', 'materialController@edit')->name('edit');
    Route::delete('{id}/delete', 'materialController@delete')->name('delete');
    Route::post('{id}/upload_material_file', 'materialController@uploadMaterialFile')->name('upload_material_file');
    Route::get('{id}/material_file', 'materialController@materialFile')->name('material_file');
    Route::delete('{id}/delete_material_file', 'materialController@deleteMaterialFile')->name('delete_material_file');
    Route::patch('{id}/update', 'materialController@update')->name('update');
    Route::get('deleteCourse/{id}', 'materialController@deleteCourse')->name('deleteCourse');
});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/user_material", 'as' => "admin.user_material."], function () {
    Route::get('/getMaterials/{material_type}/{course}', 'user_materialController@index')->name('index');
    Route::get('{id}/view', 'user_materialController@view')->name('view');
    Route::get('{id}/material_file', 'user_materialController@materialFile')->name('material_file');
});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/candidates", 'as' => "admin.candidates."], function () {
    Route::get('/{user_phase}/{user_status}', 'candidateController@index')->name('index');
    Route::post('{id}/pass', 'candidateController@pass')->name('pass');
    Route::post('{id}/fail', 'candidateController@fail')->name('fail');
    Route::get('{id}/edit/edit', 'candidateController@edit')->name('edit');
    Route::get('pilotReady', 'candidateController@pilotReady')->name('pilot_ready');
    Route::get('add', 'candidateController@add')->name('add');
    Route::get('{id}/test_details/test_details', 'candidateController@testDetails')->name('test_details');
    Route::patch('save', 'candidateController@save')->name('save');
    Route::patch('saveEdit', 'candidateController@saveEdit')->name('saveEdit');

});

Route::auth();

Route::get('/home', 'HomeController@index');

app/Http/Controllers/candidateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\User;
use Auth;
use App\User_grade;
use Hash;
use Mail;
use App\Question_answer;


class candidateController extends Controller
{
    public function index($user_phase,$user_status) {
    	$candidates = User::where('user_phase',$user_phase)->where('user_status',$user_status)->where('user_type','Volunteer')->get();
    	if($user_status == "Rejected"){
    		$candidates = User::where('user_status',$user_status)->where('user_type','Volunteer')->get();
    	}
        if($user_status == "all"){
            $candidates = User::where('user_type','Volunteer')->get();
        }
        $data = [];
        $data['partialView'] = 'candidates.list';
        $data['candidates'] = $candidates;
        $data['user_phase'] = $user_phase;
        $data['user_status'] = $user_status;
        return view('candidates.base', $data);
    }

    public function pass($id,Request $request){
    	$candidate = User::find($id);
    	if($candidate->user_phase == "pilotTest"){
    		$candidate->user_phase = "passedAll";
    		$candidate->user_status = "Approved";
            $subject = "Pilot Test Result";
    	}
    	if($candidate->user_phase == "phoneInterview"){
    		$candidate->user_phase = "pilotTest";
            $subject = "Phone Interview Result";
    	}
    	if($candidate->user_phase == "testEvaluation"){
    		$candidate->user_phase = "phoneInterview";
            $subject = "Islamic Knowledge Test Result";
    	}
    	$data = $request->input();
    	$grades = User_grade::where('user_id',$id)->first();
    	if($data['gradesFor'] == 'phoneInterview'){
    		$array = json_decode($data['answers'], true);
	    	$grades->fluency = $array[0];
	    	$grades->vocab = $array[1];
	    	$grades->grammar = $array[2];
	    	$grades->accent = $array[3];
    	}
    	if($data['gradesFor'] == 'pilotTest'){
    		
	    	
	    	$grades->pilot = $data['grade'];
	    	
    	}
    	$grades->save();

    	$candidate->save();
        Mail::send('emails.candidate_notification', ['candidate' => $candidate  ], function ($m) use ($candidate,$subject) {
            $m->from('platform@nouracademy.com', 'Nour Academy');
            $m->to($candidate->email, $candidate->name)->subject(' Volunteers | '.$subject);
        });

    }

    public function fail($id,Request $request){
    	$candidate = User::find($id);
    	$candidate->user_status = "Rejected";

    	$data = $request->input();
    	$grades = User_grade::where('user_id',$id)->first();
        if($candidate->user_phase == "testEvaluation"){
            $subject = "Islamic Knowledge Test Result";
        }
        if($candidate->user_phase == "phoneInterview"){
            $subject = "Phone Interview Result";
        }
        if($candidate->user_phase == "pilotTest"){
            $subject = "Pilot Test Result";
        }
    	if($data['gradesFor'] == 'phoneInterview'){
    		$array = json_decode($data['answers'], true);
	    	$grades->fluency = $array[0];
	    	$grades->vocab = $array[1];
	    	$grades->grammar = $array[2];
	    	$grades->accent = $array[3];
            $subject = "Phone Interview Result";
    	}
    	if($data['gradesFor'] == 'pilotTest'){
    		
	    	$subject = "Pilot Test Result";
	    	$grades->pilot = $data['grade'];
	    	
    	}
    	$grades->save();
    	$candidate->save();
        Mail::send('emails.failed', ['candidate' => $candidate  ], function ($m) use ($candidate,$subject) {
            $m->from('platform@nouracademy.com', 'Nour Academy');

            $m->to($candidate->email, $candidate->name)->subject(' Nour Academy | '.$subject);
            
        });
    }

    public function pilotReady(){
    	$candidate = Auth::user();
    	$candidate->pilot_ready = 1;
    	$candidate->save();
        $emails = ['mtarek@arabiclocalizer.com', 'm.abdelgawad@nouracademy.com','h.hafez@nouracademy.com'];
        Mail::send('emails.admin_notification', ['candidate' => $candidate  ], function ($m) use ($candidate,$emails) {
            $m->from('platform@nouracademy.com', 'Nour Academy');
            $m->to($emails)->subject(' Volunteers | Candidate ready for pilot test');
        });
    }

    public function add(){
        $data = [];
        $data['partialView'] = 'candidates.form';
        
        $data['user_phase'] = "";
        $data['user_status'] = "";
        return view('candidates.base', $data);
    }

    public function edit($id){
        $candidate = User::find($id);
        $data = [];
        $data['partialView'] = 'candidates.edit_form';
        $data['candidate'] = $candidate;
        $data['user_phase'] = "";
        $data['user_status'] = "";
        return view('candidates.base', $data);
    }

    public function save(Request $request){
        $data = $request->input();
        $candidate = new User();
        $candidate->name = $data['name'];
        $candidate->email = $data['email'];
        $candidate->phone = $data['mobile'];
        $candidate->user_type = "Volunteer";
        $candidate->dec_password = $data['password'];
        $candidate->password = Hash::make($data['password']);
        $candidate->save();
        Mail::send('emails.welcome', ['candidate' => $candidate  ], function ($m) use ($candidate) {
            $m->from('platform@nouracademy.com', 'Nour Academy');

            $m->to($candidate->email, $candidate->name)->subject(' Nour Academy | Welcome to our volunteering program');
            
        });
    }
    public function saveEdit(Request $request){
        $data = $request->input();
        $candidate = User::find($data['id']);
        $candidate->name = $data['name'];
        $candidate->email = $data['email'];
        $candidate->phone = $data['mobile'];
        $candidate->user_phase = $data['user_phase'];
        $candidate->user_status = $data['user_status'];
        
        $candidate->save();

        $grades = User_grade::where('user_id',$candidate->id)->first();
        $grades->quiz = $data['quiz'];
        $grades->accent = $data['accent'];
        $grades->grammar = $data['grammar'];
        $grades->pilot = $data['pilot'];
        $grades->vocab = $data['vocab'];
        $grades->fluency = $data['fluency'];
        $grades->save();
    }
    public function testDetails($candidate_id){
        $answers = Question_answer::where('user_id',$candidate_id)->get();
        $data = [];
        $data['partialView'] = 'candidates.test_details';
        $data['answers'] = $answers;
        
        $data['user_phase'] = "";
        $data['user_status'] = "";
        return view('candidates.base', $data);
    }
}

resources/views/candidates/base.blade.php
<?php 
if($user_phase != "passedAll"){
$i = 'candidates'; $j = $user_phase;
}else{
	$i ="volunteers" ; $j = "$user_status";
}

 ?>
@extends('admin.master')
@section('plugins_css')
<link href="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css')}}"/>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/sweetalert2/6.2.1/sweetalert2.min.css"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/jquery-nestable/jquery.nestable.css')}}"/>
<style>
.grades th{
	text-align:center !important;
}
</style>
@stop

@section('plugins_js')
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/jsvalidation.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.js')}}"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/sweetalert2/6.2.1/sweetalert2.min.js"></script>

@stop

@section('page_js')
<script>
var pageAttributes = {
    indexUrl: "",
}

</script>
<script type="text/javascript" src="{{asset('assets/ajaxForms.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/scripts.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/admin/pages/scripts/candidates.js')}}"></script>
@endSection

@section('add_inits')

@stop

@section('title')
Candidates
@stop

@section('page_title')
Candidates
@stop

@section('page_title_small')

@stop

@section('content')
@include($partialView)
@stop

resources/views/candidates/edit_form.blade.php
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> New  </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <div  id="main-form" novalidate method="POST" class="larajsval form"> 
            <div class="form-body">
            <div class="mt-element-ribbon bg-grey-steel">
                                                <div class="ribbon ribbon-border-hor ribbon-clip ribbon-color-primary uppercase">
                                                    <div class="ribbon-sub ribbon-clip"></div> Main Info </div>
                                                <p class="ribbon-content">
                                                <div class="form-group">
                                                  <div class="form-group">
                    <label>Name</label>
                    <input name="name" class="form-control" value="{{$candidate->name}}">
                    <input type="hidden" name="id" id="hiddenField" value="{{$candidate->id}}" />
                                                  </div>
                <div class="form-group">
                    <label>Email</label>
                    <input name="email" type="email" class="form-control" value="{{$candidate->email}}" >
                </div>
                <div class="form-group">
                    <label>Mobile</label>
                    <input name="mobile" class="form-control" value="{{$candidate->phone}}" >
                </div>
                <div class="form-group">
                    <label>Phase</label>
                    <select name="user_phase" class="form-control" >
                    	<option value="testing" <?php if($candidate->user_phase == "testing"){?> selected="selected"<?php ;}?>>Testing</option>
                    	<option value="testEvaluation" <?php if($candidate->user_phase == "testEvaluation"){?> selected="selected"<?php ;}?>>Test Evaluation</option>
                    	<option value="phoneInterview" <?php if($candidate->user_phase == "phoneInterview"){?> selected="selected"<?php ;}?>>Phone Interview</option>
                    	<option value="pilotTest" <?php if($candidate->user_phase == "pilotTest"){?> selected="selected"<?php ;}?>>Pilot Test</option>
                    	<option value="passedAll" <?php if($candidate->user_phase == "passedAll"){?> selected="selected"<?php ;}?>>Passed All</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Status</label>
                    <select name="user_status" class="form-control" >
                    	<option value="Pending" <?php if($candidate->user_status == "Pending"){?> selected="selected"<?php ;}?>>Pending</option>
                    	<option value="Approved" <?php if($candidate->user_status == "Approved"){?> selected="selected"<?php ;}?>>Approved</option>
                    	<option value="Rejected" <?php if($candidate->user_status == "Rejected"){?> selected="selected"<?php ;}?>>Rejected</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Quiz grade</label>
                    <input name="quiz" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->quiz}}@endif" >
                </div>
                <div class="form-group">
                    <label>Fluency</label>
                    <input name="fluency" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->fluency}}@endif" >
                </div>
                <div class="form-group">
                    <label>Vocab</label>
                    <input name="vocab" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->vocab}}@endif" >
                </div>
                <div class="form-group">
                    <label>Grammar</label>
                    <input name="grammar" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->grammar}}@endif" >
                </div>
                <div class="form-group">
                    <label>Accent</label>
                    <input name="accent" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->accent}}@endif" >
                </div>
                <div class="form-group">
                    <label>Pilot test grade</label>
                    <input name="pilot" class="form-control" value="@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->pilot}}@endif" >
                </div>
               
                
                
                
                
                </p>
                
                                            </div>
                                            
                                            </div>
            

            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                    <button type="button" class="btn btn-lg green" id="save-all-edit" data-action="{{route('admin.candidates.saveEdit')}}">Save</button>
                </div>
            </div>
        </div>
        <!-- END FORM-->
    </div>
</div>

resources/views/candidates/form.blade.php
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i> New  </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <div  id="main-form" novalidate method="POST" class="larajsval form"> 
            <div class="form-body">
            <div class="mt-element-ribbon bg-grey-steel">
                                                <div class="ribbon ribbon-border-hor ribbon-clip ribbon-color-primary uppercase">
                                                    <div class="ribbon-sub ribbon-clip"></div> Main Info </div>
                                                <p class="ribbon-content">
                                                <div class="form-group">
                                                  <div class="form-group">
                    <label>Name</label>
                    <input name="name" class="form-control" >
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input name="email" type="email" class="form-control" >
                </div>
                <div class="form-group">
                    <label>mobile</label>
                    <input name="mobile" class="form-control" >
                </div>
                <div class="form-group">
                    <label>password</label>
                    <input name="password" type="password" class="form-control" >
                </div>
                
                
                
                
                </p>
                
                                            </div>
                                            
                                            </div>
            

            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                    <button type="button" class="btn btn-lg green" id="save-all" data-action="{{route('admin.candidates.save')}}">Save</button>
                </div>
            </div>
        </div>
        <!-- END FORM-->
    </div>
</div>
@include('quizzes.templates')

resources/views/candidates/list.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>Candidates
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                           <a href="{{route('admin.candidates.add')}}" class="pjax-link"><button class="btn green" >

                            Add New Candidate <i class="fa fa-plus"></i>
                        </button>
                        </a>                  
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt" >
            <thead>
                <tr class="tr-head">
                    <th valign="middle">
                        Title
                    </th>
                    <th valign="middle">Email</th>
                    <th valign="middle">Mobile</th>
                    <?php if($user_phase == "testEvaluation" || $user_phase == "phoneInterview"){?> <th valign="middle">Test Degree</th> <?php ;}?>
                    <?php if($user_phase == "pilotTest"){?><th valign="middle">Pilot</th><?php ;}?>
                   
                    <?php if($user_status == "Rejected" || $user_status == "all" ){?>
                    <th valign="middle">Phase &amp; Grades</th>
                    <?php ;}?>
                    
                    <th valign="middle">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($candidates as $candidate)
                <tr class="odd gradeX" id="data-row-{{$candidate->id}}" data-user_id = "{{$candidate->id}}">
                    <td valign="middle">
                        {{$candidate->name}}
                    </td>
                    <td valign="middle">{{$candidate->email}}</td>
                    <td valign="middle">{{$candidate->phone}}</td>
                    <?php if($candidate->user_phase == "testEvaluation" || $user_phase == "phoneInterview"){?><td valign="middle">{{$candidate->getGrades->quiz}}</td><?php ;}?>
                    <?php if($user_phase == "pilotTest"){?><td valign="middle"><?php if($candidate->pilot_ready == 1){?>Ready<?php ;}else{?>Not ready<?php ;}?></td><?php ;}?>
                    
                    <?php if($user_status == "Rejected" || $user_status == "all" ){?><td valign="middle">
                      <table width="100%" border="0" cellspacing="0" cellpadding="0" class="grades">
                        <tr>
                        <th align="center" scope="col">Phase</th>
                        <th align="center" scope="col">Status</th>
                          <th align="center" scope="col">Quiz</th>
                          <th align="center" scope="col">Fluency</th>
                          <th align="center" scope="col">Vocab</th>
                          <th align="center" scope="col">Grammar</th>
                          <th align="center" scope="col">Accent</th>
                          <th align="center" scope="col">Pilot</th>
                        </tr>
                        <tr>
                        <td align="center">{{$candidate->user_phase}}</td>
                        <td align="center">{{$candidate->user_status}}</td>
                          <td align="center">@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->quiz}}@endif</td>
                          <td align="center">@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->fluency}}@endif</td>
                          <td align="center">@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->vocab}}@endif</td>
                          <td align="center">@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->grammar}}@endif</td>
                          <td align="center">@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->accent}}@endif</td>
                          <td align="center">@if(isset($candidate->getGrades->quiz)){{$candidate->getGrades->pilot}}@endif</td>
                        </tr>
                      </table></td><?php ;}?>
                    
                    <td valign="middle">
                    @if($candidate->user_status =="Pending" && $candidate->user_phase !="testing")
                    <a href="{{route('admin.candidates.pass',['id'=>$candidate->id])}}" data-phase = "{{$candidate->user_phase}}" class="btn green candidate-change-status" ><i class="fa fa-check"></i> Pass</a>
                    <a href="{{route('admin.candidates.fail',['id'=>$candidate->id])}}" data-phase = "{{$candidate->user_phase}}" class="btn red candidate-change-status" ><i class="fa fa-remove"></i> Fail</a> 
                    
                    @endif
                    <?php if($user_status == "all" ){?>
                   	  <a href="{{route('admin.candidates.edit',['id'=>$candidate->id])}}"  class="btn green pjax-link" ><i class="fa fa-edit"></i> edit</a> 	
                    <?php ;}?>
                    <a href="{{route('admin.candidates.test_details',['id'=>$candidate->id])}}"  class="btn blue pjax-link" ><i class="fa fa-edit"></i> test details</a> 	
                    
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/candidates/test_details.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>Test Details
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                           <a href="{{route('admin.candidates.add')}}" class="pjax-link"><button class="btn green" >

                            Add New Candidate <i class="fa fa-plus"></i>
                        </button>
                        </a>                  
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt" >
            <thead>
                <tr class="tr-head">
                    <th valign="middle">Question</th>
                    <th valign="middle">Student Degree</th>
                    <th valign="middle">Max degree</th>
                    <th valign="middle">Start time</th>
                    <th valign="middle">End time</th>
                </tr>
            </thead>
            <tbody>
                @foreach($answers as $answer)
                <tr class="odd gradeX" id="data-row-{{$answer->id}}" data-user_id = "{{$answer->id}}">
                    <td valign="middle">
                    {{$answer->getQuestion->content}}
                        
                    </td>
                    <td valign="middle">{{$answer->degree}}</td>
                    <td valign="middle">{{$answer->getQuestion->weight}}</td>
                    <td valign="middle">{{$answer->getEntry->start_time}}</td>
                    <td valign="middle">{{$answer->getEntry->end_time}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/candidates/view.blade.php
	<iframe width="100%" height="1000" src="{{$path}}" frameborder="0" scrolling="no"></iframe>