app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'userController@index')->name('index');
Route::get('/admin/current_status', 'userController@currentStatus')->name('currentStatus');

Route::group(['middleware' => ['auth'], 'prefix' => "admin/quizzes", 'as' => "admin.quizzes."], function () {
    Route::get('/', function () {
        return redirect('/admin/quizzes/1/edit');
    });
    Route::get('{id}/edit', 'quizController@edit')->name('edit');
    Route::post('question_add/{quiz_id}', 'quizController@addQuestion')->name('question_add');
    Route::post('answer_add/{quiz_id}', 'quizController@addAnswer')->name('answer_add');
    Route::get('answers/{question_id}', 'quizController@answers')->name('answers');
    Route::delete('{id}/delete', 'quizController@delete')->name('delete');
    Route::post('quizzes/{id}/init_question', 'quizController@initQuestion')->name('init_question');
    Route::post('{id}/upload_question_file', 'quizController@uploadQuestionFile')->name('upload_question_file');
    Route::post('{id}/upload_answer_file', 'quizController@uploadAnswerFile')->name('upload_answer_file');
    Route::get('{id}/question_file', 'quizController@questionFile')->name('question_file');
    Route::get('{id}/answer_file', 'quizController@answerFile')->name('answer_file');
    Route::delete('{id}/delete_question_file', 'quizController@deleteQuestionFile')->name('delete_question_file');
    Route::delete('{id}/delete_answer_file', 'quizController@deleteAnswerFile')->name('delete_answer_file');
    Route::delete('{id}/delete_course_image', 'quizController@deleteCourseImage')->name('delete_course_image');
    Route::delete('{id}/delete_promo', 'quizController@deletePromo')->name('delete_promo');
    Route::patch('{id}/update', 'quizController@update')->name('update');
    Route::patch('{id}/update_answers', 'quizController@updateAnswers')->name('update_answers');
});


Route::group(['middleware' => ['auth'], 'prefix' => 'admin/users', 'as' => 'admin.users.'], function () {
    Route::get('/{status}', 'UserController@index')->name('index');

    Route::post('init', 'UserController@init')->name('init');
    Route::get('{id}/edit', 'UserController@edit')->name('edit');
    Route::delete('{id}/delete', 'UserController@delete')->name('delete');
    Route::post('{id}/recommission', 'UserController@recommission')->name('recommission');
    Route::get('create', 'UserController@create')->name('create');
    Route::delete('delete_multiple', 'UserController@deleteMultiple')->name('delete_multiple');
    Route::post('store', 'UserController@store')->name('store');
    Route::patch('{id}/update', 'UserController@update')->name('update');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'admin/user_test', 'as' => 'admin.user_test.'], function () {
    Route::get('/', 'volunteersTestController@index')->name('index');

    Route::get('startTest/{user_id}', 'volunteersTestController@startTest')->name('start_test');
    Route::post('answerQuestion', 'volunteersTestController@answerQuestion')->name('answer_question');
    Route::get('endTest', 'volunteersTestController@endTest')->name('end_test');
    
});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/material", 'as' => "admin.material."], function () {
    Route::get('/', 'materialController@index')->name('index');
    Route::post('init', 'materialController@init')->name('init');
    Route::get('{id}/edit', 'materialController@edit')->name('edit');
    Route::delete('{id}/delete', 'materialController@delete')->name('delete');
    Route::post('{id}/upload_material_file', 'materialController@uploadMaterialFile')->name('upload_material_file');
    Route::get('{id}/material_file', 'materialController@materialFile')->name('material_file');
    Route::delete('{id}/delete_material_file', 'materialController@deleteMaterialFile')->name('delete_material_file');
    Route::patch('{id}/update', 'materialController@update')->name('update');
    Route::get('deleteCourse/{id}', 'materialController@deleteCourse')->name('deleteCourse');
});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/user_material", 'as' => "admin.user_material."], function () {
    Route::get('/getMaterials/{material_type}/{course}', 'user_materialController@index')->name('index');
    Route::get('{id}/view', 'user_materialController@view')->name('view');
    Route::get('{id}/material_file', 'user_materialController@materialFile')->name('material_file');
});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/candidates", 'as' => "admin.candidates."], function () {
    Route::get('/{user_phase}/{user_status}', 'candidateController@index')->name('index');
    Route::post('{id}/pass', 'candidateController@pass')->name('pass');
    Route::post('{id}/fail', 'candidateController@fail')->name('fail');
    Route::get('{id}/edit/edit', 'candidateController@edit')->name('edit');
    Route::get('pilotReady', 'candidateController@pilotReady')->name('pilot_ready');
    Route::get('add', 'candidateController@add')->name('add');
    Route::get('{id}/test_details/test_details', 'candidateController@testDetails')->name('test_details');
    Route::patch('save', 'candidateController@save')->name('save');
    Route::patch('saveEdit', 'candidateController@saveEdit')->name('saveEdit');

});

Route::auth();

Route::get('/home', 'HomeController@index');

app/Http/Controllers/user_materialController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Material;
use File;
use ZipArchive;
use RecursiveIteratorIterator;
use FilesystemIterator;
use Storage;
use Response;

class user_materialController extends Controller
{
    public function index($material_type,$course) {
        $data = [];
        $data['partialView'] = 'user_material.list';
        if($course ==0){
            $data['materials'] = Material::where('material_type',$material_type)->orderBy('material_order', 'asc')->get();
        }else{
            $data['materials'] = Material::where('material_type',$material_type)->where('course_id',$course)->orderBy('material_order', 'asc')->get();

        }
        $data['material_type'] = $material_type;
        $data['course'] = $course;
        return view('user_material.base', $data);
    }


    public function view($id) {
        $material = Material::findOrFail($id);

        $path = '/uploads/material/material_file/'.$id.'/index.html';


	    
	    

        $data = [];

        $data['partialView'] = 'user_material.view';
        $data['material'] = $material;
        $data['material_type'] = "";
        $data['course'] = "";
        $data['path'] = $path;
        return view('user_material.base', $data);
    }
    
    public function materialFile($id) {
        $material = Material::findOrFail($id);
        if ($material->materialFile()) {
            return response()->download($material->materialFile()->path, $material->materialFile()->name);
        }
        abort(404);
    }
    

    
}

resources/views/user_material/base.blade.php
<?php 
if(isset($material_type)){
	$i = $material_type;
}
if(isset($course)){
	$j = $course;
}?>
@extends('admin.master')
@section('plugins_css')
<link href="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/sweetAlert/sweetalert.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/jquery-nestable/jquery.nestable.css')}}"/>
@stop

@section('plugins_js')
<script type="text/javascript" src="{{asset('assets/global/scripts/datatable.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/jsvalidation.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/sweetAlert/sweetalert.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/jquery-nestable/jquery.nestable.js')}}"></script>
@stop

@section('page_js')
<script>
var pageAttributes = {
    indexUrl: "",
}

</script>
<script type="text/javascript" src="{{asset('assets/ajaxForms.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/scripts.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/admin/pages/scripts/user_material.js')}}"></script>
@endSection

@section('add_inits')

@stop

@section('title')
 Materials
@stop

@section('page_title')
 Materials
@stop

@section('page_title_small')

@stop

@section('content')
@include($partialView)
@stop

resources/views/user_material/form.blade.php
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>@if($material)Edit @else New @endif </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <div  id="main-form" novalidate method="POST" class="larajsval form"> 
            <div class="form-body">
            <div class="mt-element-ribbon bg-grey-steel">
                                                <div class="ribbon ribbon-border-hor ribbon-clip ribbon-color-primary uppercase">
                                                    <div class="ribbon-sub ribbon-clip"></div> Main Info </div>
                                                <p class="ribbon-content">
                                                <div class="form-group">
                                                  <div class="form-group">
                    <label>Name</label>
                    <input name="material_name" class="form-control" value="{{$material->name}}">
                </div>
                <div class="form-group">
                    <label>Order</label>
                    <input name="material_order" class="form-control" value="{{$material->material_order}}">
                </div>
                <div class="form-group">
                    <label>Type</label>
                    <select name="material_type" class="form-control material_type">
                    	<option value="" >Select Type</option>
                        
                        <option value="File"  <?php if($material->type == "File"){?> selected="selected"<?php ;}?>>File Or HTML5</option>
                        <option value="Video" <?php if($material->type == "Video"){?> selected="selected"<?php ;}?>>Youtube Video</option>
                    </select>
                </div>
                
                <div class="<?php if($material->type !="Video"){?>hide<?php ;}?> form-group youtube">
                    <label>Youtube ID</label>
                    <input name="youtube_id" class="form-control" value="{{$material->youtube_id}}">
                </div>
                <div class="<?php if($material->type !="File"){?>hide<?php ;}?> form-group fileUploading">
                    <label >Attach File</label>
                    <input type="file" class="hidden fileinput"
                           data-action="{{route('admin.material.upload_material_file',['id'=>$material->id])}}" 
                           >
                    <div class="row">
                        <div class="col-md-8">
                            <span class="filenameplaceholder">
                                @if($material->content)
                                <a class="btn btn-primary filename" href="{{route('admin.material.material_file',['id'=>$material->id])}}" >
                                  <i class="fa fa-edit"></i>  Download File
                                </a>
                                @else
                                No file selected
                                @endif
                            </span>
                            <div class="progress-bar progress-bar-success hidden" role="progressbar"  style="width: 0%">
                                <span>0%</span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <button type="button" class="btn btn-primary filepicker pull-right {{$material->content?'hidden':''}}">
                                Select File
                            </button>
                            <button class="btn btn-danger pull-right cancel hidden">Cancel</button>
                            <button class="btn btn-danger pull-right removefile {{$material->content?'':'hidden'}}" 
                                    data-action="{{route('admin.material.delete_material_file',['id'=>$material->id])}}"
                                    >
                                Detach file
                            </button>
                        </div>
                        
                    </div>
                </div>
                </p>
                
                                            </div>
                                            
                                            </div>
            

            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                    <button type="button" class="btn btn-lg green" id="save-all" data-action="{{route('admin.material.update',['id'=>$material->id])}}">Save</button>
                </div>
            </div>
        </div>
        <!-- END FORM-->
    </div>
</div>
@include('quizzes.templates')

resources/views/user_material/list.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>Materials
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                                             
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" >
            <thead>
                <tr class="tr-head">
                    <th valign="middle">
                        Title
                    </th>
                    <th valign="middle">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($materials as $material)
                <tr class="odd gradeX" id="data-row-{{$material->id}}">
                    <td valign="middle">
                        {{$material->name}}
                    </td>
                    <td valign="middle">
                    <?php if($material->type == "File" && $material->content_type == "HTML5"){?><a href="{{route('admin.user_material.view',['id'=>$material->id])}}" class="btn green pjax-link" ><i class="fa fa-eye"></i> View</a><?php ;}?>
                    <?php if($material->type == "Video"){?><a href="https://www.youtube.com/watch?v={{$material->youtube_id}}" class="popup btn green" ><i class="fa fa-youtube"></i> Watch Video</a><?php ;}?>
                    <?php if($material->type == "File" && $material->content_type == "Other"){?><a href="{{route('admin.user_material.material_file',['id'=>$material->id])}}" class="btn green" ><i class="fa fa-download"></i> Download Material</a><?php ;}?>
                    </td>
                </tr>
                @endforeach
            <tr></tbody>
        </table>
    </div>
</div>

resources/views/user_material/view.blade.php
	<iframe width="100%" height="1000" src="{{$path}}" frameborder="0" scrolling="no"></iframe>