app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'userController@index')->name('index');
Route::get('/admin/current_status', 'userController@currentStatus')->name('currentStatus');

Route::group(['middleware' => ['auth'], 'prefix' => "admin/quizzes", 'as' => "admin.quizzes."], function () {
    Route::get('/', function () {
        return redirect('/admin/quizzes/1/edit');
    });
    Route::get('{id}/edit', 'quizController@edit')->name('edit');
    Route::post('question_add/{quiz_id}', 'quizController@addQuestion')->name('question_add');
    Route::post('answer_add/{quiz_id}', 'quizController@addAnswer')->name('answer_add');
    Route::get('answers/{question_id}', 'quizController@answers')->name('answers');
    Route::delete('{id}/delete', 'quizController@delete')->name('delete');
    Route::post('quizzes/{id}/init_question', 'quizController@initQuestion')->name('init_question');
    Route::post('{id}/upload_question_file', 'quizController@uploadQuestionFile')->name('upload_question_file');
    Route::post('{id}/upload_answer_file', 'quizController@uploadAnswerFile')->name('upload_answer_file');
    Route::get('{id}/question_file', 'quizController@questionFile')->name('question_file');
    Route::get('{id}/answer_file', 'quizController@answerFile')->name('answer_file');
    Route::delete('{id}/delete_question_file', 'quizController@deleteQuestionFile')->name('delete_question_file');
    Route::delete('{id}/delete_answer_file', 'quizController@deleteAnswerFile')->name('delete_answer_file');
    Route::delete('{id}/delete_course_image', 'quizController@deleteCourseImage')->name('delete_course_image');
    Route::delete('{id}/delete_promo', 'quizController@deletePromo')->name('delete_promo');
    Route::patch('{id}/update', 'quizController@update')->name('update');
    Route::patch('{id}/update_answers', 'quizController@updateAnswers')->name('update_answers');
});


Route::group(['middleware' => ['auth'], 'prefix' => 'admin/users', 'as' => 'admin.users.'], function () {
    Route::get('/{status}', 'UserController@index')->name('index');

    Route::post('init', 'UserController@init')->name('init');
    Route::get('{id}/edit', 'UserController@edit')->name('edit');
    Route::delete('{id}/delete', 'UserController@delete')->name('delete');
    Route::post('{id}/recommission', 'UserController@recommission')->name('recommission');
    Route::get('create', 'UserController@create')->name('create');
    Route::delete('delete_multiple', 'UserController@deleteMultiple')->name('delete_multiple');
    Route::post('store', 'UserController@store')->name('store');
    Route::patch('{id}/update', 'UserController@update')->name('update');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'admin/user_test', 'as' => 'admin.user_test.'], function () {
    Route::get('/', 'volunteersTestController@index')->name('index');

    Route::get('startTest/{user_id}', 'volunteersTestController@startTest')->name('start_test');
    Route::post('answerQuestion', 'volunteersTestController@answerQuestion')->name('answer_question');
    Route::get('endTest', 'volunteersTestController@endTest')->name('end_test');
    
});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/material", 'as' => "admin.material."], function () {
    Route::get('/', 'materialController@index')->name('index');
    Route::post('init', 'materialController@init')->name('init');
    Route::get('{id}/edit', 'materialController@edit')->name('edit');
    Route::delete('{id}/delete', 'materialController@delete')->name('delete');
    Route::post('{id}/upload_material_file', 'materialController@uploadMaterialFile')->name('upload_material_file');
    Route::get('{id}/material_file', 'materialController@materialFile')->name('material_file');
    Route::delete('{id}/delete_material_file', 'materialController@deleteMaterialFile')->name('delete_material_file');
    Route::patch('{id}/update', 'materialController@update')->name('update');
    Route::get('deleteCourse/{id}', 'materialController@deleteCourse')->name('deleteCourse');
});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/user_material", 'as' => "admin.user_material."], function () {
    Route::get('/getMaterials/{material_type}/{course}', 'user_materialController@index')->name('index');
    Route::get('{id}/view', 'user_materialController@view')->name('view');
    Route::get('{id}/material_file', 'user_materialController@materialFile')->name('material_file');
});

Route::group(['middleware' => ['auth'], 'prefix' => "admin/candidates", 'as' => "admin.candidates."], function () {
    Route::get('/{user_phase}/{user_status}', 'candidateController@index')->name('index');
    Route::post('{id}/pass', 'candidateController@pass')->name('pass');
    Route::post('{id}/fail', 'candidateController@fail')->name('fail');
    Route::get('{id}/edit/edit', 'candidateController@edit')->name('edit');
    Route::get('pilotReady', 'candidateController@pilotReady')->name('pilot_ready');
    Route::get('add', 'candidateController@add')->name('add');
    Route::get('{id}/test_details/test_details', 'candidateController@testDetails')->name('test_details');
    Route::patch('save', 'candidateController@save')->name('save');
    Route::patch('saveEdit', 'candidateController@saveEdit')->name('saveEdit');

});

Route::auth();

Route::get('/home', 'HomeController@index');

app/Material.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Material extends Model
{
    private $materialFile = null;


    public static function boot() {
        parent::boot();
        static::deleting(function ($course) {
            
            $course->deleteMaterialFile();
            
            
            
            
        });
    }
    public function getCourse(){
        return $this->hasOne('App\Course','id','course_id');
    }
    public function materialFile() {
        if (is_null($this->content)) {
            return null;
        }
        if (is_null($this->materialFile)) {
            $this->materialFile = File::find($this->content);
            return $this->materialFile;
        }
        return $this->materialFile;
    }

    public function deleteMaterialFile() {
        if ($this->materialFile()) {
            $this->materialFile()->delete();
            $this->content = null;
            $this->save();
        }
    }
}

app/Http/Controllers/materialController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Material;
use App\File;
use ZipArchive;
use RecursiveIteratorIterator;
use FilesystemIterator;
use App\Course;

class materialController extends Controller
{
    public function deleteCourse($id){
        $course = Course::where('name',$id)->delete();
    }
    public function index() {
        $data = [];
        $data['partialView'] = 'material.list';
        $data['materials'] = Material::orderBy('material_order', 'asc')->get();
        return view('material.base', $data);
    }

    public function init() {
        $material = new Material();
        $material->save();
        return response(['url' => route('admin.material.edit', ['id' => $material->id])]);
    }

    public function edit($id) {
        $material = Material::findOrFail($id);
        $courses = Course::orderBy('name')->get();
        $data = [];
        $data['partialView'] = 'material.form';
        $data['material'] = $material;
        $data['courses'] = $courses;
        return view('material.base', $data);
    }
    public function uploadMaterialFile($id, Request $request) {
        $material = Material::findOrFail($id);
        $uploadedFile = $request->file('file');
        $dirPath = public_path('uploads/material/material_file/'.$material->id);
        $saveName = md5(microtime(true) . uniqid(str_random(3)) . str_random(10));
        $uploadedFile->move($dirPath, $saveName);
        $file = new File();
        $file->path = $dirPath . '/' . $saveName;
        $file->name = $uploadedFile->getClientOriginalName();
        $file->save();
        $ext = pathinfo($file->name, PATHINFO_EXTENSION);
        $material->content_type = "Other";
        if(strtolower($ext) == "zip"){
            $material->content_type = "HTML5";
        	$zip = new ZipArchive();
			$x = $zip->open($file->path);
			if ($x === true) {
				$zip->extractTo($dirPath); // change this to the correct site path
				$zip->close();
		
				
			}
			

        }

        $material->content = $file->id;
        $material->type = "File";
        $material->save();
        $responseData = [];
        $responseData['remove_action'] = route('admin.material.delete_material_file', ['id' => $material->id]);
        $responseData['download_action'] = route('admin.material.material_file', ['id' => $material]);
        $responseData['file_name'] = $file->name;
        return response()->json($responseData);
    }
    public function materialFile($id) {
        $material = Material::findOrFail($id);
        if ($material->materialFile()) {
            return response()->download($material->materialFile()->path, $material->materialFile()->name);
        }
        abort(404);
    }
    public function deleteMaterialFile($id) {
        Material::findOrFail($id)->deleteMaterialFile();
        $dirPath = public_path('uploads/material/material_file/'.$id);
        $this->recursiveRmDir($dirPath);
        
    }
    public function update(Request $request, $id) {
        $course = Course::where('name',$request->course_id)->first();

        if(!$course){
            $course = new Course();
            $course->name = $request->course_id;
            $course->save();
        }
        $material = Material::findOrFail($id);
        $material->name = $request->name;
        $material->material_type = $request->material_type;
        $material->type = $request->type;
        $material->material_order = $request->order;
        $material->youtube_id = $request->youtube_id;
        $material->course_id = $course->id;
        $material->save();
        
        $responseData = [];
        $responseData['url'] = "/admin/material";
        return response()->json($responseData);
    }

    public function delete($id) {
        Material::findOrFail($id)->delete();
    }

    public function recursiveRmDir($dir)
	{
	    $iterator = new RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS), \RecursiveIteratorIterator::CHILD_FIRST);
	    foreach ($iterator as $filename => $fileInfo) {
	        if ($fileInfo->isDir()) {
	            rmdir($filename);
	        } else {
	            unlink($filename);
	        }
	    }
	    rmdir($dir);
}
}

resources/views/material/base.blade.php
<?php $i = "material"; $j = "material"; ?>
@extends('admin.master')
@section('plugins_css')
<link href="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.css')}}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/datatables.min.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/sweetAlert/sweetalert.css')}}"/>
<link rel="stylesheet" type="text/css" href="{{asset('assets/global/plugins/jquery-nestable/jquery.nestable.css')}}"/>
@stop

@section('plugins_js')
<script type="text/javascript" src="{{asset('assets/global/scripts/datatable.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/datatables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/datetimepicker/bootstrap-datetimepicker.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/jsvalidation.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/bootstrap-toastr/toastr.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/sweetAlert/sweetalert.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/global/plugins/jquery-nestable/jquery.nestable.js')}}"></script>
@stop

@section('page_js')
<script>
var pageAttributes = {
    indexUrl: "",
}

</script>
<script type="text/javascript" src="{{asset('assets/ajaxForms.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/scripts.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/admin/pages/scripts/material.js')}}"></script>
@endSection

@section('add_inits')

@stop

@section('title')
Training Materials
@stop

@section('page_title')
Training Materials
@stop

@section('page_title_small')

@stop

@section('content')
@include($partialView)
@stop

resources/views/material/form.blade.php
<div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-gift"></i>@if($material)Edit @else New @endif </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <div  id="main-form" novalidate method="POST" class="larajsval form"> 
            <div class="form-body">
            <div class="mt-element-ribbon bg-grey-steel">
                                                <div class="ribbon ribbon-border-hor ribbon-clip ribbon-color-primary uppercase">
                                                    <div class="ribbon-sub ribbon-clip"></div> Main Info </div>
                                                <p class="ribbon-content">
                                                <div class="form-group">
                                                
                                                <div class="form-group">
                    <label>Type </label>
                    <select name="material_type1" class="form-control material_type1">
                    	<option value="" >Select Material Type</option>
                        
                        <option value="Training"  <?php if($material->material_type == "Training"){?> selected="selected"<?php ;}?>>Training Material</option>
                        <option value="Course" <?php if($material->material_type == "Course"){?> selected="selected"<?php ;}?>>Course Material</option>
                    </select>
                </div>
                <div class="form-group courseType <?php if($material->material_type != "Course"){?>hide<?php ;}?>">
                <div class="row">
                <div class="col-md-8">
                    <label>Course </label>
                    <select name="course_id" class="form-control editable-select">
                    	
                        @foreach($courses as $course)
                        <option value="{{$course->id}}"  <?php if($material->course_id == $course->id){?> selected="selected"<?php ;}?>>{{$course->name}}</option>
                        @endforeach
                    </select>
                    </div>
                    <div class="col-md-4">
                    
                    <button type="button" class="btn btn-sm red <?php if($material->course_id == ""){?>hide<?php ;}?>"  id="delete-course" style="margin-top:27px;" >Delete</button>
                    </div>
                </div>
                </div>
                                                  <div class="form-group">
                    <label>Name</label>
                    <input name="material_name" class="form-control" value="{{$material->name}}">
                </div>
                <div class="form-group">
                    <label>Order</label>
                    <input name="material_order" class="form-control" value="{{$material->material_order}}">
                </div>
                <div class="form-group">
                    <label>Type</label>
                    <select name="material_type" class="form-control material_type">
                    	<option value="" >Select Type</option>
                        
                        <option value="File"  <?php if($material->type == "File"){?> selected="selected"<?php ;}?>>File Or HTML5</option>
                        <option value="Video" <?php if($material->type == "Video"){?> selected="selected"<?php ;}?>>Youtube Video</option>
                    </select>
                </div>
                
                <div class="<?php if($material->type !="Video"){?>hide<?php ;}?> form-group youtube">
                    <label>Youtube ID</label>
                    <input name="youtube_id" class="form-control" value="{{$material->youtube_id}}">
                </div>
                <div class="<?php if($material->type !="File"){?>hide<?php ;}?> form-group fileUploading">
                    <label >Attach File</label>
                    <input type="file" class="hidden fileinput"
                           data-action="{{route('admin.material.upload_material_file',['id'=>$material->id])}}" 
                           >
                    <div class="row">
                        <div class="col-md-8">
                            <span class="filenameplaceholder">
                                @if($material->content)
                                <a class="btn btn-primary filename" href="{{route('admin.material.material_file',['id'=>$material->id])}}" >
                                  <i class="fa fa-edit"></i>  Download File
                                </a>
                                @else
                                No file selected
                                @endif
                            </span>
                            <div class="progress-bar progress-bar-success hidden" role="progressbar"  style="width: 0%">
                                <span>0%</span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <button type="button" class="btn btn-primary filepicker pull-right {{$material->content?'hidden':''}}">
                                Select File
                            </button>
                            <button class="btn btn-danger pull-right cancel hidden">Cancel</button>
                            <button class="btn btn-danger pull-right removefile {{$material->content?'':'hidden'}}" 
                                    data-action="{{route('admin.material.delete_material_file',['id'=>$material->id])}}"
                                    >
                                Detach file
                            </button>
                        </div>
                        
                    </div>
                </div>
                </p>
                
                                            </div>
                                            
                                            </div>
            

            </div>
            <div class="form-actions">
                <div class="btn-set pull-right">
                    <button type="button" class="btn btn-lg green" id="save-all" data-action="{{route('admin.material.update',['id'=>$material->id])}}">Save</button>
                </div>
            </div>
        </div>
        <!-- END FORM-->
    </div>
</div>
@include('quizzes.templates')

resources/views/material/list.blade.php
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>Materials
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
        </div>
    </div>
    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <button class="btn green" id="add_new" data-action="{{route('admin.material.init')}}"
>
                            Add New <i class="fa fa-plus"></i>
                        </button>                        
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
        <table class="table table-striped table-bordered table-hover table-dt" id="table-dt" >
            <thead>
                <tr class="tr-head">
                    <th valign="middle">
                        Title
                    </th>
                    <th valign="middle">Course</th>
                    <th valign="middle">Type</th>
                    <th valign="middle">File Type</th>
                    <th valign="middle">Order</th>
                    <th valign="middle">
                        Created at
                    </th>
                    <th valign="middle">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach($materials as $material)
                <tr class="odd gradeX" id="data-row-{{$material->id}}">
                    <td valign="middle">
                        {{$material->name}}
                    </td>
                    <td valign="middle"><?php if(isset($material->getCourse->name)){?>{{$material->getCourse->name}}<?php ;}?></td>
                    <td valign="middle">{{$material->material_type}} Material</td>
                    <td valign="middle">{{$material->type}}</td>
                    <td valign="middle">{{$material->material_order}}</td>
                    <td valign="middle">
                        {{$material->created_at}}
                    </td>
                    <td valign="middle">
                        <a href="{{route('admin.material.edit',['id'=>$material->id])}}" class="btn green pjax-link" ><i class="fa fa-edit"></i> Edit</a> 
                        <a href="{{route('admin.material.delete',['id'=>$material->id])}}" class="btn red remove-course" ><i class="fa fa-remove"></i> Delete</a> 
                    </td>
                </tr>
                @endforeach
            </tbody>
                        
        </table>
    </div>
</div>